# Logging level for this application.
log_level: INFO

ldap:
    host:
    port: "389"
    use_ssl: "true"
    user:
    password:
    dn_search:

workers: {}

database:
    path: db.duckdb

logging:
  default:
    filters:
      warning:
        class: loggate.LowerLogLevelFilter
        level: WARNING

    formatters:
      colored:
        class: loggate.LogColorFormatter

    handlers:
      stdout:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: colored
        filters:
          - warning
      stderr:
        class: logging.StreamHandler
        stream: ext://sys.stderr
        formatter: colored
        level: WARNING
    loggers:
        root:
          level: INFO
          handlers:
            - stdout
            - stderr
