services:
  frontend:
    build:
      context: .
      dockerfile: ../frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - wg_command

  backend:
    build:
      context: .
      dockerfile: ../backend/Dockerfile
    ports:
      - "5000:5000"
    user: vscode
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - wg_command
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - frontend

networks:
  wg_command:
    driver: bridge
    driver_opts:
      # Adjust MTU if needed (e.g., connection by WireGuard)
      com.docker.network.driver.mtu: 1420
