services:
  frontend:
    build:
      context: .
      dockerfile: ../frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway

  backend:
    build:
      context: .
      dockerfile: ../backend/Dockerfile
    ports:
      - "5000:5000"
    user: vscode
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - frontend

  db:
    image: postgres:16
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

  adminer:
    image: adminer
    restart: always

networks:
  default:
    driver: bridge
    driver_opts:
      # Adjust MTU if needed (e.g., connection by WireGuard)
      com.docker.network.driver.mtu: 1420

volumes:
  db-data: