services:
  frontend:
    build:
      context: .
      dockerfile: ../frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - wg_command

  backend:
    build:
      context: .
      dockerfile: ../backend/Dockerfile
    ports:
      - "5000:5000"
    user: vscode
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - wg_command
    depends_on:
      - frontend

networks:
  wg_command:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420